# Generated by Django 3.2.7 on 2021-09-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20210917_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='end_date',
            field=models.DateField(null=True, verbose_name='End Date'),
        ),
    ]
