# Generated by Django 3.2.7 on 2021-09-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_todo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('COMPLETE', 'COMPLETE'), ('PENDING', 'PENDING')], max_length=15),
        ),
    ]
